language: php

php:
  # We don't support PHP <5.3, so no need to test that.
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - composer install

script: phpunit --coverage-text tests/
